

#actuator
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env, beans


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eris
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    tomcat:
      connection-properties: logger=Slf4j
  devtools:
    restart:
      enabled: true


server:
  error:
    include-message: always
